platform :ios, '12.1'

target 'Consumer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'MyFramework', :path => '../MyFramework'
  #pod 'MyFramework', :git => 'https://github.com/aliakhtar49/MyFramework.git', :tag => '1.0.4'
pod 'MyFramework', :git => 'https://github.com/aliakhtar49/MyFramework.git', :commit => 'c9d79d0b2e99f3771f9973a0393736363145cacd'

  # Pods for Consumer

end
