platform :ios, '12.1'

target 'Consumer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'MyFramework', :path => '../MyFramework'
  pod 'MyFramework', :git => 'https://github.com/aliakhtar49/MyFramework.git', :tag => '1.0.3'

  # Pods for Consumer

end
