# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

source 'https://github.com/aliakhtar49/PrivateFrameworkSpecRepo.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'PrivateFrameworkSpecRepoConsumer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrivateFrameworkSpecRepoConsumer
  pod 'ModuleNetwork'
  pod 'ModuleExtension'

end
